import Foundation

/// Normalizes message text and queries into the two forms the search index stores.
///
/// Toj's users type Tajik Cyrillic, Russian, and Latin transliteration — frequently on a Russian
/// keyboard that has no ҷ ғ ҳ қ keys, so "тоҷикӣ" gets typed as "точики". The index therefore holds
/// two forms of every text column:
///
/// - ``exact(_:)`` — case folded and Latin diacritics removed. What the user actually wrote.
/// - ``foldedForm(_:)`` — additionally collapses the six Tajik letters onto the Russian keyboard
///   lookalikes users substitute for them.
///
/// ## Everything here is measured, not remembered
///
/// ``SearchUnicodeTables`` is generated by probing the FTS5 tokenizer inside our own SQLCipher pod
/// (`scripts/generate-search-unicode-tables.py`). Nothing in this file calls `String.lowercased()`,
/// `String.folding(options:)`, or `Unicode.Scalar.Properties`: those consult whichever ICU the
/// runtime links, so they can shift between OS versions and cannot be reproduced in Bun.
///
/// The Tajik table is the one hand-authored rule, and it exists precisely *because* unicode61 does
/// not fold Cyrillic — the tokenizer leaves ҷ ғ ҳ қ ӣ ӯ untouched. Do not add ё→е or й→и without an
/// explicit product decision; the tokenizer leaves those alone too, and folding them merges
/// distinct Russian words.
///
/// ## Three scalar classes
///
/// unicode61 does not divide scalars in two. ``ScalarClass`` mirrors what it actually does:
///
/// - ``ScalarClass/token`` — part of a token.
/// - ``ScalarClass/ignored`` — a diacritic dropped *without ending the token*, so `a` + U+0301 +
///   `b` is the single token `ab`. Twenty-five scalars.
/// - ``ScalarClass/separator`` — ends the token.
///
/// Treating ignored diacritics as separators — as an earlier version did — splits `e◌́galite◌́`
/// into two tokens where the engine produces one, so stored terms and query terms diverge. One
/// state machine, ``forEachToken(in:_:)``, drives both ``tokens(_:)`` and
/// ``highlightRanges(of:in:)`` so they can never disagree about where a token starts.
///
/// ## Invariants
///
/// 1. **Idempotent** — `exact(exact(x)) == exact(x)`, likewise `foldedForm`.
/// 2. **Scalar-preserving** — one scalar in, exactly one out. Every fold is one-to-one, and
///    ignored and separator scalars pass through untouched rather than being stripped; the state
///    machine skips them at tokenize time instead. That is what makes ``highlightRanges(of:in:)``
///    an identity mapping rather than an offset table.
/// 3. **Runtime-independent** — output depends only on pinned tables, never on `Locale` or ICU.
nonisolated enum SearchTextNormalizer {
    /// Bumping this triggers an incremental background reindex on next launch.
    ///
    /// It must cover **every** rule that can change a token: ``tajikFolds``, the transliteration
    /// tables, *and* the generated ``SearchUnicodeTables``. Regenerating those — for a new SQLite
    /// version, or a tokenizer change in `SearchIndexSchema` — is token-affecting and requires a
    /// bump here even though this file did not change.
    /// `testTokenAffectingTablesMatchPinnedDigest` fails when any of them moves without one.
    ///
    /// - Version 2 replaced runtime ICU case mapping with probed tables and cut the fold set to the
    ///   six Tajik letters.
    /// - Version 3 introduced the three-class model. Version 2 classified the 25 ignored diacritics
    ///   as separators, so any text containing a combining mark tokenized differently from the
    ///   index that stored it.
    static let version = 3

    /// The six Tajik letters absent from a Russian keyboard layout, mapped to what users type
    /// instead. unicode61 folds none of them — see `testUnicode61DoesNotFoldCyrillic`.
    static let tajikFolds: [Unicode.Scalar: Unicode.Scalar] = [
        "\u{04B7}": "\u{0447}",  // ҷ -> ч
        "\u{0493}": "\u{0433}",  // ғ -> г
        "\u{04B3}": "\u{0445}",  // ҳ -> х
        "\u{049B}": "\u{043A}",  // қ -> к
        "\u{04E3}": "\u{0438}",  // ӣ -> и
        "\u{04EF}": "\u{0443}",  // ӯ -> у
    ]

    /// How the tokenizer treats a scalar.
    enum ScalarClass: Equatable {
        /// Contributes to the current token.
        case token
        /// Dropped in place; the surrounding token continues across it.
        case ignored
        /// Ends the current token.
        case separator
    }

    // MARK: - Normalization

    /// Case folded with Latin diacritics removed, preserving scalar count.
    static func exact(_ text: String) -> String {
        String(String.UnicodeScalarView(text.unicodeScalars.map(baseFold)))
    }

    /// ``exact(_:)`` with the six Tajik letters collapsed onto their Russian lookalikes.
    static func foldedForm(_ text: String) -> String {
        String(String.UnicodeScalarView(text.unicodeScalars.map { tajikFold(baseFold($0)) }))
    }

    /// The folded form, or `nil` when identical to ``exact(_:)``.
    ///
    /// Callers deciding *whether* text contains anything Tajik want this. The indexer does not: it
    /// writes ``foldedForm(_:)`` unconditionally so the folded tier is a complete fallback index.
    static func folded(_ text: String) -> String? {
        let exactForm = exact(text)
        let foldedForm = String(String.UnicodeScalarView(exactForm.unicodeScalars.map(tajikFold)))
        return foldedForm == exactForm ? nil : foldedForm
    }

    // MARK: - Tokenization

    static func classify(_ scalar: Unicode.Scalar) -> ScalarClass {
        if SearchUnicodeTables.ignoredScalars.contains(scalar.value) { return .ignored }
        return isSeparator(scalar.value) ? .separator : .token
    }

    /// Walks `text`, invoking `body` once per token with the token's text and the half-open scalar
    /// offsets it occupies in `text`.
    ///
    /// The single definition of "where a token begins and ends". Both ``tokens(_:)`` and
    /// ``highlightRanges(of:in:)`` go through it, so highlighting cannot drift from matching.
    ///
    /// Ignored scalars neither extend nor end a token: they are skipped, and because a token only
    /// opens on a ``ScalarClass/token`` scalar, a leading diacritic cannot start one.
    static func forEachToken(
        in text: String, _ body: (String, Range<Int>) -> Void
    ) {
        var current = String.UnicodeScalarView()
        var start = 0
        var end = 0

        for (offset, scalar) in text.unicodeScalars.enumerated() {
            switch classify(scalar) {
            case .token:
                if current.isEmpty { start = offset }
                current.append(scalar)
                end = offset + 1
            case .ignored:
                continue
            case .separator:
                if !current.isEmpty {
                    body(String(current), start..<end)
                    current = String.UnicodeScalarView()
                }
            }
        }
        if !current.isEmpty { body(String(current), start..<end) }
    }

    /// Splits normalized text into the tokens `unicode61` would produce.
    static func tokens(_ text: String) -> [String] {
        var tokens: [String] = []
        forEachToken(in: text) { token, _ in tokens.append(token) }
        return tokens
    }

    // MARK: - Highlighting

    /// Locates `query`'s tokens inside `original`, returning ranges into the **original,
    /// unmodified** text so display keeps its accents and letter forms.
    ///
    /// This is the payoff of scalar preservation. Folding maps scalar *i* of the original to scalar
    /// *i* of the folded form, so a match found in folded space is the same range in original
    /// space — no offset table, no drift. `cafe` against `Café` folds to `cafe`, matches at scalars
    /// 0..<4, and hands back the range covering `Café` with the accent intact.
    ///
    /// Because the token walker skips ignored diacritics rather than stopping at them, a match
    /// spans them: `cafe` highlights all of `Cafe◌́`, and `egalite` highlights all of `e◌́galite◌́`.
    ///
    /// Matching is token-aligned and prefix-based, mirroring the MATCH pattern, and considers the
    /// same Latin transliteration alternative the folded tier searches — so `chon`, which reaches
    /// `ҷон` through the index, also highlights it.
    static func highlightRanges(of query: String, in original: String) -> [Range<String.Index>] {
        var needles = Set(tokens(foldedForm(query)))
        if let candidate = cyrillicCandidate(query) {
            needles.formUnion(tokens(foldedForm(candidate)))
        }
        guard !needles.isEmpty else { return [] }

        let folded = foldedForm(original)
        var boundaries = Array(original.unicodeScalars.indices)
        boundaries.append(original.unicodeScalars.endIndex)
        guard folded.unicodeScalars.count == boundaries.count - 1 else { return [] }

        var ranges: [Range<String.Index>] = []
        forEachToken(in: folded) { token, span in
            guard needles.contains(where: token.hasPrefix) else { return }
            // Extend across trailing ignored diacritics so an accent is not orphaned outside the
            // highlight when the source is in decomposed form.
            var end = span.upperBound
            let scalars = Array(folded.unicodeScalars)
            while end < scalars.count, classify(scalars[end]) == .ignored { end += 1 }
            ranges.append(boundaries[span.lowerBound]..<boundaries[end])
        }
        return ranges
    }

    // MARK: - Latin transliteration

    /// Transliterates a Latin query into its likely Cyrillic spelling, or `nil` when the input is
    /// not plausibly transliteration.
    ///
    /// Tajik speakers routinely type `salom` / `chon` for салом / ҷон, especially without a
    /// Cyrillic keyboard installed. This widens the *folded* tier rather than adding a third index
    /// column, so `j` and `q` map to ч and к rather than ҷ and қ.
    ///
    /// Not scalar-preserving: digraphs collapse two scalars into one. Never use for offsets.
    static func cyrillicCandidate(_ text: String) -> String? {
        let lowered = exact(text)
        guard lowered.unicodeScalars.contains(where: isLatinLetter),
              !lowered.unicodeScalars.contains(where: isCyrillicLetter) else { return nil }

        var result = String.UnicodeScalarView()
        let scalars = Array(lowered.unicodeScalars)
        var index = 0
        while index < scalars.count {
            var matched = false
            // Longest digraph first: "shch" before "sh" before "s".
            for length in stride(from: min(4, scalars.count - index), through: 2, by: -1) {
                let candidate = String(String.UnicodeScalarView(scalars[index..<(index + length)]))
                if let replacement = Self.latinDigraphs[candidate] {
                    result.append(replacement)
                    index += length
                    matched = true
                    break
                }
            }
            if matched { continue }
            result.append(Self.latinLetters[scalars[index]] ?? scalars[index])
            index += 1
        }
        let candidate = String(result)
        return candidate == lowered ? nil : candidate
    }

    // MARK: - Scalar mapping

    private static let foldTable: [UInt32: UInt32] = {
        var table = [UInt32: UInt32](minimumCapacity: SearchUnicodeTables.foldPairs.count / 2)
        for index in stride(from: 0, to: SearchUnicodeTables.foldPairs.count, by: 2) {
            table[SearchUnicodeTables.foldPairs[index]] = SearchUnicodeTables.foldPairs[index + 1]
        }
        return table
    }()

    private static func baseFold(_ scalar: Unicode.Scalar) -> Unicode.Scalar {
        guard let folded = foldTable[scalar.value],
              let mapped = Unicode.Scalar(folded) else { return scalar }
        return mapped
    }

    private static func tajikFold(_ scalar: Unicode.Scalar) -> Unicode.Scalar {
        tajikFolds[scalar] ?? scalar
    }

    private static func isSeparator(_ value: UInt32) -> Bool {
        let ranges = SearchUnicodeTables.separatorRanges
        var low = 0
        var high = ranges.count / 2 - 1
        while low <= high {
            let mid = (low + high) / 2
            if value < ranges[mid * 2] {
                high = mid - 1
            } else if value > ranges[mid * 2 + 1] {
                low = mid + 1
            } else {
                return true
            }
        }
        return false
    }

    private static func isLatinLetter(_ scalar: Unicode.Scalar) -> Bool {
        ("a"..."z").contains(scalar) || ("A"..."Z").contains(scalar)
    }

    private static func isCyrillicLetter(_ scalar: Unicode.Scalar) -> Bool {
        (0x0400...0x04FF).contains(scalar.value)
    }

    // MARK: - Transliteration tables

    static let latinDigraphs: [String: Unicode.Scalar] = [
        "shch": "\u{0449}",  // щ
        "sch": "\u{0449}",   // щ
        "ch": "\u{0447}",    // ч
        "sh": "\u{0448}",    // ш
        "kh": "\u{0445}",    // х
        "zh": "\u{0436}",    // ж
        "ts": "\u{0446}",    // ц
        "gh": "\u{0433}",    // ғ folds to г
        "yu": "\u{044E}",    // ю
        "ya": "\u{044F}",    // я
    ]

    static let latinLetters: [Unicode.Scalar: Unicode.Scalar] = [
        "a": "\u{0430}", "b": "\u{0431}", "v": "\u{0432}", "g": "\u{0433}",
        "d": "\u{0434}", "e": "\u{0435}", "z": "\u{0437}", "i": "\u{0438}",
        "y": "\u{0438}", "k": "\u{043A}", "l": "\u{043B}", "m": "\u{043C}",
        "n": "\u{043D}", "o": "\u{043E}", "p": "\u{043F}", "r": "\u{0440}",
        "s": "\u{0441}", "t": "\u{0442}", "u": "\u{0443}", "f": "\u{0444}",
        "h": "\u{0445}", "c": "\u{0446}", "j": "\u{0447}", "q": "\u{043A}",
        "w": "\u{0432}", "x": "\u{0445}",
    ]
}
