#!/usr/bin/env python3
"""Regenerates Toj/Core/Search/SearchUnicodeTables.swift from the bundled SQLCipher tokenizer.

Compiles scripts/probe-fts5-tokenizer.c against Pods/SQLCipher/sqlite3.c — the amalgamation that
ships in the app, not the system sqlite3 — and probes every valid Unicode scalar in context.

Three classes come out, and the distinction between the last two cannot be observed by probing a
scalar on its own:

    token       part of a token, folded through the emitted fold table
    ignored     removed in place without ending the token ("a" U+0301 "b" -> "ab")
    separator   ends the token ("a" U+05B0 "b" -> "a", "b")

Token characters outnumber the rest a hundred to one — unicode61 treats unassigned scalars as
alphanumeric — so the tables store separators and ignored scalars explicitly and default to token.

Requires `pod install` to have run. Keep TOKENIZE in step with SearchIndexSchema.tokenize; changing
it changes what tokens exist and requires bumping SearchTextNormalizer.version.

    python3 scripts/generate-search-unicode-tables.py > Toj/Core/Search/SearchUnicodeTables.swift
"""

import os
import subprocess
import sys
import tempfile

TOKENIZE = "unicode61 remove_diacritics 2"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CLASS_SEPARATOR, CLASS_TOKEN, CLASS_IGNORED = 0, 1, 2


def build_and_run():
    amalgamation = os.path.join(ROOT, "Pods", "SQLCipher", "sqlite3.c")
    if not os.path.exists(amalgamation):
        sys.exit("Pods/SQLCipher/sqlite3.c missing — run `pod install` first")

    binary = os.path.join(tempfile.mkdtemp(), "fts5probe")
    subprocess.run(
        [
            "cc", "-O1", "-o", binary,
            os.path.join(ROOT, "scripts", "probe-fts5-tokenizer.c"), amalgamation,
            "-I", os.path.join(ROOT, "Pods", "SQLCipher"),
            "-DSQLITE_ENABLE_FTS5", "-DSQLITE_HAS_CODEC", "-DSQLCIPHER_CRYPTO_CC",
            "-DSQLITE_THREADSAFE=1", "-DSQLITE_TEMP_STORE=2", "-DSQLITE_OMIT_LOAD_EXTENSION",
            "-DSQLITE_EXTRA_INIT=sqlcipher_extra_init",
            "-DSQLITE_EXTRA_SHUTDOWN=sqlcipher_extra_shutdown",
            "-framework", "Security", "-framework", "Foundation",
        ],
        check=True,
    )
    out = subprocess.run([binary, TOKENIZE], capture_output=True, text=True, check=True)

    classes, folds = {}, {}
    for line in out.stdout.splitlines():
        if not line:
            continue
        scalar, kind, folded = line.split("\t")
        scalar, kind = int(scalar), int(kind)
        classes[scalar] = kind
        if kind == CLASS_TOKEN and folded != "-" and int(folded) != scalar:
            folds[scalar] = int(folded)
    return classes, folds


def contiguous(values):
    spans = []
    for value in values:
        if spans and value == spans[-1][1] + 1:
            spans[-1][1] = value
        else:
            spans.append([value, value])
    return spans


def literal(values, per_line=12):
    return "\n".join(
        "        " + " ".join(f"0x{v:04X}," for v in values[i : i + per_line])
        for i in range(0, len(values), per_line)
    )


def main():
    classes, folds = build_and_run()
    expected = 0x110000 - 0x800  # every scalar except the surrogate range
    if len(classes) != expected:
        sys.exit(f"probed {len(classes)} scalars, expected {expected}")

    bad = {s: f for s, f in folds.items() if f > 0x10FFFF}
    if bad:
        sys.exit(f"non-scalar fold targets: {list(bad.items())[:5]}")

    separators = sorted(s for s, k in classes.items() if k == CLASS_SEPARATOR)
    ignored = sorted(s for s, k in classes.items() if k == CLASS_IGNORED)
    spans = contiguous(separators)
    flat_separators = [v for span in spans for v in span]
    flat_folds = [v for s, f in sorted(folds.items()) for v in (s, f)]

    print(f'''// Generated by scripts/generate-search-unicode-tables.py — do not edit by hand.
//
// Probed from the FTS5 tokenizer inside our own SQLCipher pod, configured as
// "{TOKENIZE}" exactly as SearchIndexSchema configures the index. These tables therefore
// describe what the engine does rather than what Unicode says it should, and they are pinned: they
// do not vary with the ICU version Foundation links at runtime, so Swift and the Bun server can
// agree byte for byte.
//
// All {len(classes)} valid scalars were probed in context as "a<scalar>b", which is the only way to
// tell an ignored diacritic from a separator — both produce no token in isolation, but only a
// separator ends the surrounding token.
//
// {len(classes) - len(separators) - len(ignored)} token characters, {len(separators)} separators in
// {len(spans)} ranges, {len(ignored)} ignored scalars, {len(folds)} folds — every one of them a
// single scalar to a single scalar, which is what lets SearchTextNormalizer preserve scalar count
// and map highlight ranges by identity.

nonisolated enum SearchUnicodeTables {{
    /// Inclusive `[lower, upper, ...]` pairs of scalars that end a token, sorted.
    ///
    /// Separators are stored rather than token characters because unicode61 treats unassigned
    /// scalars as alphanumeric, so token characters outnumber separators by more than a hundred to
    /// one. Anything absent from these ranges and from ``ignoredScalars`` is a token character.
    static let separatorRanges: [UInt32] = [
{literal(flat_separators)}
    ]

    /// Diacritics `remove_diacritics=2` strips *without* ending the token, so "a" U+0301 "b" is the
    /// single token "ab". Sorted; small enough to scan linearly.
    ///
    /// An ignored scalar cannot begin a token: with nothing open it is simply dropped, which is why
    /// a leading diacritic behaves like a separator even though it is not one.
    static let ignoredScalars: [UInt32] = [
{literal(ignored)}
    ]

    /// Fold pairs `[from, to, ...]`, sorted by `from`. Case folding and Latin diacritic removal
    /// combined, so `É` and `é` both arrive at `e`.
    ///
    /// Cyrillic is almost entirely absent: unicode61 folds neither ё nor й nor ӣ nor ӯ. That is why
    /// the Tajik folds in SearchTextNormalizer exist as a separate, explicit step.
    static let foldPairs: [UInt32] = [
{literal(flat_folds)}
    ]
}}''')


if __name__ == "__main__":
    main()
