#!/usr/bin/env python3
"""Regenerates server/src/search-normalizer-vectors.json.

Local search and server search must tokenize identically or a query returns different rows
depending on which one answered it. This file is the contract between them: an independent
reimplementation of SearchTextNormalizer's rules, from the same probed tokenizer data, emitted as
input/expected pairs.

`SearchTextNormalizerTests` asserts Swift reproduces every vector, and `server/src/search.test.ts`
will assert the same of Bun. Because the expectations here are produced by a *separate*
implementation rather than by dumping Swift's output, agreement is evidence of correctness rather
than a tautology.

    python3 scripts/generate-search-normalizer-vectors.py > server/src/search-normalizer-vectors.json
"""

import json
import subprocess
import sys

TOKENIZE = "unicode61 remove_diacritics 2"
NORMALIZER_VERSION = 2

# The six Tajik letters a Russian keyboard cannot produce. unicode61 folds none of them.
TAJIK_FOLDS = {0x04B7: 0x0447, 0x0493: 0x0433, 0x04B3: 0x0445,
               0x049B: 0x043A, 0x04E3: 0x0438, 0x04EF: 0x0443}

CASES = [
    "Салом, ҷони ман!", "ТОҶИКӢ", "тоҷикӣ", "точики",
    "Ғафуров қишлоқ ҳаво ӯро", "Привет, как дела?", "ёлка йогурт",
    "Hello World", "Café", "cafe", "café", "égalite",
    "naïve", "Straße", "İstanbul", "ıssız",
    "½ ² 5", "abcdef", "🇹🇯 salom 👋", "file2024.pdf",
    "", "   ", "!!!???", "ǅ ǆ Ǆ", "МОСКВА москва",
]


def probe_tables():
    points = [c for c in range(0x20, 0x10000) if not (0xD800 <= c <= 0xDFFF)]
    points += list(range(0x1F300, 0x1F320))
    script = [
        "PRAGMA journal_mode=OFF;",
        f'CREATE VIRTUAL TABLE t USING fts5(x, tokenize="{TOKENIZE}");',
        "BEGIN;",
    ]
    script += [f"INSERT INTO t(rowid,x) VALUES({c},char({c}));" for c in points]
    script += ["COMMIT;", "CREATE VIRTUAL TABLE v USING fts5vocab(t, instance);", "SELECT doc,term FROM v;"]
    out = subprocess.run(["sqlite3", ":memory:"], input="\n".join(script), capture_output=True, text=True)
    if out.returncode:
        sys.exit(f"sqlite3 failed: {out.stderr[:400]}")

    terms = {}
    for line in out.stdout.split("\n"):
        if line and "|" in line:
            doc, term = line.split("|", 1)
            terms[int(doc)] = term
    token_chars = {c for c in points if c in terms}
    folds = {c: ord(terms[c]) for c in token_chars if terms[c] != chr(c)}
    return token_chars, folds


def main():
    token_chars, folds = probe_tables()

    def base_fold(text):
        return "".join(chr(folds.get(ord(ch), ord(ch))) for ch in text)

    def tajik_fold(text):
        return "".join(chr(TAJIK_FOLDS.get(ord(ch), ord(ch))) for ch in text)

    def tokenize(text):
        out, cur = [], []
        for ch in text:
            if ord(ch) in token_chars:
                cur.append(ch)
            elif cur:
                out.append("".join(cur)); cur = []
        if cur:
            out.append("".join(cur))
        return out

    vectors = []
    for case in CASES:
        exact = base_fold(case)
        folded = tajik_fold(exact)
        vectors.append({
            "input": case,
            "exact": exact,
            "folded": None if folded == exact else folded,
            "tokens": tokenize(folded),
        })
        assert len(exact) == len(case), f"scalar count changed for {case!r}"

    print(json.dumps({
        "normalizerVersion": NORMALIZER_VERSION,
        "tokenize": TOKENIZE,
        "note": "Generated by scripts/generate-search-normalizer-vectors.py. "
                "Swift and Bun must both reproduce every vector exactly. "
                "'folded' is null when it equals 'exact'.",
        "vectors": vectors,
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
