#!/usr/bin/env python3
"""Regenerates Toj/Core/Search/SearchUnicodeTables.swift.

The search normalizer must agree with the FTS5 tokenizer that indexes its output, and later with
the Bun implementation that backs server search. Rather than hand-transcribe Unicode rules — the
approach that produced the wrong table the first time — this probes the *actual* tokenizer and
emits what it observes.

Every scalar in the BMP (plus supplementary samples) is inserted as its own row into an FTS5 table
configured exactly as `SearchIndexSchema` configures the real one. `fts5vocab(instance)` then
reports the term each scalar produced, which yields two facts per scalar:

  * whether it is a token character (it produced a term at all), and
  * what `unicode61 remove_diacritics 2` folds it to.

Run with the tokenizer settings in TOKENIZE below kept in step with SearchIndexSchema. If the
emitted table changes, bump SearchTextNormalizer.version — the on-device index must be rebuilt.

    python3 scripts/generate-search-unicode-tables.py > Toj/Core/Search/SearchUnicodeTables.swift
"""

import subprocess
import sys

TOKENIZE = "unicode61 remove_diacritics 2"

# The BMP in full, plus samples from the supplementary planes: emoji (So, expected separators),
# Linear B and Adlam (L*, expected token characters). Surrogates cannot be passed to char().
CODEPOINTS = [c for c in range(0x20, 0x10000) if not (0xD800 <= c <= 0xDFFF)]
CODEPOINTS += list(range(0x1F300, 0x1F320))
CODEPOINTS += list(range(0x10000, 0x10010))
CODEPOINTS += list(range(0x1E900, 0x1E910))


def probe():
    script = [
        "PRAGMA journal_mode=OFF;",
        f'CREATE VIRTUAL TABLE t USING fts5(x, tokenize="{TOKENIZE}");',
        "BEGIN;",
    ]
    script += [f"INSERT INTO t(rowid,x) VALUES({c},char({c}));" for c in CODEPOINTS]
    script += [
        "COMMIT;",
        "CREATE VIRTUAL TABLE v USING fts5vocab(t, instance);",
        "SELECT doc,term FROM v;",
    ]
    out = subprocess.run(
        ["sqlite3", ":memory:"], input="\n".join(script), capture_output=True, text=True
    )
    if out.returncode:
        sys.exit(f"sqlite3 failed: {out.stderr[:400]}")

    terms = {}
    for line in out.stdout.split("\n"):
        if line and "|" in line:
            doc, term = line.split("|", 1)
            terms[int(doc)] = term
    return terms


def contiguous(values):
    spans = []
    for value in values:
        if spans and value == spans[-1][1] + 1:
            spans[-1][1] = value
        else:
            spans.append([value, value])
    return spans


def literal(values, per_line=12):
    lines, indent = [], "        "
    for i in range(0, len(values), per_line):
        lines.append(indent + " ".join(f"0x{v:04X}," for v in values[i : i + per_line]))
    return "\n".join(lines)


def main():
    terms = probe()
    token_chars = sorted(c for c in CODEPOINTS if c in terms)
    folds = {c: terms[c] for c in token_chars if terms[c] != chr(c)}

    non_1to1 = {c: t for c, t in folds.items() if len(t) != 1}
    if non_1to1:
        sys.exit(
            "scalar preservation is violated by: "
            + ", ".join(f"U+{c:04X}->{t!r}" for c, t in list(non_1to1.items())[:10])
        )

    spans = contiguous(token_chars)
    flat_ranges = [v for span in spans for v in span]
    flat_folds = [v for c, t in sorted(folds.items()) for v in (c, ord(t))]

    print(f'''// Generated by scripts/generate-search-unicode-tables.py — do not edit by hand.
//
// Probed from a live FTS5 table tokenized as "{TOKENIZE}", which is the configuration
// SearchIndexSchema applies to the real index. These tables therefore describe what the tokenizer
// actually does rather than what Unicode says it should, and they are pinned: they do not vary
// with the ICU version Foundation happens to link at runtime, so Swift and the Bun server can
// agree byte for byte.
//
// Coverage: every BMP scalar plus supplementary samples. {len(token_chars)} token characters in
// {len(spans)} ranges, {len(folds)} folds — all of them one scalar to one scalar, which is what
// lets SearchTextNormalizer preserve scalar count and map highlight ranges by identity.

nonisolated enum SearchUnicodeTables {{
    /// Half-open pairs of token-character ranges: `[lower, upper, lower, upper, ...]`, inclusive
    /// on both ends and sorted. A scalar absent from every range is a separator. This matches
    /// unicode61's L*, N* and Co classes — notably CJK and private-use scalars are token
    /// characters while emoji and whitespace are not.
    static let tokenRanges: [UInt32] = [
{literal(flat_ranges)}
    ]

    /// Fold pairs `[from, to, from, to, ...]`, sorted by `from`. Combines case folding and Latin
    /// diacritic removal, so `É` and `é` both arrive at `e`. Cyrillic is deliberately almost
    /// absent — unicode61 folds neither ё nor й nor ӣ nor ӯ, which is why the Tajik folds in
    /// SearchTextNormalizer exist as a separate, explicit step.
    static let foldPairs: [UInt32] = [
{literal(flat_folds)}
    ]
}}''')


if __name__ == "__main__":
    main()
