#!/usr/bin/env python3
"""Regenerates server/src/search-normalizer-vectors.json.

Local search and server search must tokenize identically or a query returns different rows
depending on which one answered it. This file is the contract between them: an independent
reimplementation of SearchTextNormalizer's rules, from the same probed tokenizer data, emitted as
input/expected pairs.

`SearchTextNormalizerTests` asserts Swift reproduces every vector, and `server/src/search.test.ts`
will assert the same of Bun. Because the expectations here are produced by a *separate*
implementation rather than by dumping Swift's output, agreement is evidence of correctness rather
than a tautology.

    python3 scripts/generate-search-normalizer-vectors.py > server/src/search-normalizer-vectors.json
"""

import json
import os
import subprocess
import sys

def manifest():
    """The one place the tokenizer configuration and normalizer version live."""
    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "Toj/Core/Search/search-tokenizer-manifest.json")
    with open(path) as handle:
        return json.load(handle)


TOKENIZE = manifest()["tokenizer"]
NORMALIZER_VERSION = manifest()["normalizerVersion"]

# The six Tajik letters a Russian keyboard cannot produce. unicode61 folds none of them.
TAJIK_FOLDS = {0x04B7: 0x0447, 0x0493: 0x0433, 0x04B3: 0x0445,
               0x049B: 0x043A, 0x04E3: 0x0438, 0x04EF: 0x0443}

CASES = [
    "Салом, ҷони ман!", "ТОҶИКӢ", "тоҷикӣ", "точики",
    "Ғафуров қишлоқ ҳаво ӯро", "Привет, как дела?", "ёлка йогурт",
    "Hello World", "Café", "cafe", "café", "égalite",
    "naïve", "Straße", "İstanbul", "ıssız",
    "½ ² 5", "abcdef", "🇹🇯 salom 👋", "file2024.pdf",
    "", "   ", "!!!???", "ǅ ǆ Ǆ", "МОСКВА москва",
    # Decomposed diacritics exercise the ignored class: an ignored scalar must not end the token,
    # so these collapse to one token rather than splitting in two.
    "e\u0301galite\u0301", "a\u0301b", "\u0301ab", "ab\u0301", "a\u0301\u0308b",
    # U+05B0 is a combining mark unicode61 does not accept, so it separates.
    "a\u05b0b",
    # Private use is a token class; it joins rather than splitting.
    "abc\ue000def",
]


def probe_tables():
    """Reuses the context-aware probe so both generators read the same measured classes."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "tables", os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "generate-search-unicode-tables.py"))
    tables = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(tables)
    classes, folds = tables.build_and_run()
    return classes, folds


def main():
    classes, folds = probe_tables()
    TOKEN, IGNORED = 1, 2

    def base_fold(text):
        return "".join(chr(folds.get(ord(ch), ord(ch))) for ch in text)

    def tajik_fold(text):
        return "".join(chr(TAJIK_FOLDS.get(ord(ch), ord(ch))) for ch in text)

    def tokenize(text):
        """The three-class state machine. Ignored diacritics neither extend nor end a token."""
        out, cur = [], []
        for ch in text:
            kind = classes.get(ord(ch), TOKEN)
            if kind == TOKEN:
                cur.append(ch)
            elif kind == IGNORED:
                continue
            elif cur:
                out.append("".join(cur)); cur = []
        if cur:
            out.append("".join(cur))
        return out

    vectors = []
    for case in CASES:
        exact = base_fold(case)
        folded = tajik_fold(exact)
        vectors.append({
            "input": case,
            "exact": exact,
            "folded": None if folded == exact else folded,
            "tokens": tokenize(folded),
        })
        assert len(exact) == len(case), f"scalar count changed for {case!r}"

    print(json.dumps({
        "normalizerVersion": NORMALIZER_VERSION,
        "tokenize": TOKENIZE,
        "note": "Generated by scripts/generate-search-normalizer-vectors.py. "
                "Swift and Bun must both reproduce every vector exactly. "
                "'folded' is null when it equals 'exact'.",
        "vectors": vectors,
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
