#!/usr/bin/env bash
# Verifies the committed search tables still describe the locked SQLCipher pod.
#
# The tokenizer tables and normalizer vectors are generated by probing the FTS5 implementation
# inside Pods/SQLCipher. Nothing stops someone editing them by hand, and nothing stops a pod bump
# silently changing what the tokenizer does. Either way the on-device index would disagree with the
# code that queries it, and the failure is invisible until a user's search returns the wrong rows.
#
# So this regenerates both artifacts and fails on any diff, then enforces that a token-affecting
# change is accompanied by a normalizer-version bump — because without one, existing installs keep
# an index built under the old rules and never rebuild it.
#
#     scripts/verify-search-tables.sh [base-ref]
#
# base-ref defaults to origin/main and is only used for the version-bump check.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

BASE_REF="${1:-origin/main}"
TABLES="Toj/Core/Search/SearchUnicodeTables.swift"
VECTORS="server/src/search-normalizer-vectors.json"
NORMALIZER="Toj/Core/Search/SearchTextNormalizer.swift"

if [[ ! -f Pods/SQLCipher/sqlite3.c ]]; then
  echo "Pods/SQLCipher/sqlite3.c missing — run 'pod install' first" >&2
  exit 2
fi

echo "==> Regenerating from Pods/SQLCipher ($(grep -m1 '#define SQLITE_VERSION ' Pods/SQLCipher/sqlite3.h | awk '{print $3}'))"

fail=0
for pair in "$TABLES:generate-search-unicode-tables.py" "$VECTORS:generate-search-normalizer-vectors.py"; do
  path="${pair%%:*}"
  script="${pair##*:}"
  tmp="$(mktemp)"
  python3 "scripts/$script" > "$tmp"
  if ! diff -q "$path" "$tmp" > /dev/null; then
    echo "FAIL: $path does not match a fresh probe of the locked pod." >&2
    echo "      Regenerate with: python3 scripts/$script > $path" >&2
    diff -u "$path" "$tmp" | head -40 >&2
    fail=1
  else
    echo "  ok  $path"
  fi
  rm -f "$tmp"
done
[[ $fail -eq 0 ]] || exit 1

# A token-affecting change without a version bump leaves every existing install querying a new
# ruleset against an index built under the old one. The digest test catches an edited table; only
# this catches an edited table *plus* an obligingly updated digest.
if git rev-parse --verify --quiet "$BASE_REF" > /dev/null; then
  changed="$(git diff --name-only "$BASE_REF"...HEAD -- "$TABLES" "$NORMALIZER" || true)"
  if [[ -n "$changed" ]]; then
    # `|| true` is load-bearing: under `set -o pipefail` a missing file at the base ref fails the
    # pipeline, and `set -e` would abandon the check entirely instead of reporting it.
    old_version="$( { git show "$BASE_REF:$NORMALIZER" 2>/dev/null || true; } \
      | sed -n 's/.*static let version = \([0-9]*\).*/\1/p' | head -1 || true)"
    new_version="$(sed -n 's/.*static let version = \([0-9]*\).*/\1/p' "$NORMALIZER" | head -1)"

    if [[ -n "$old_version" && "$old_version" == "$new_version" ]]; then
      # Only token-affecting hunks matter; a documentation edit to the normalizer does not.
      if git diff "$BASE_REF"...HEAD -- "$TABLES" | grep -qE '^[+-] *0x' \
        || git diff "$BASE_REF"...HEAD -- "$NORMALIZER" \
             | grep -qE '^[+-].*(tajikFolds|latinDigraphs|latinLetters|u\{04|u\{05)'; then
        echo "FAIL: token-affecting tables changed but SearchTextNormalizer.version is still $new_version." >&2
        echo "      Bump it, regenerate $VECTORS, and update pinnedTableDigest." >&2
        exit 1
      fi
    fi
    echo "  ok  normalizer version $new_version (was ${old_version:-unknown})"
  fi
else
  echo "  --  skipping version-bump check: $BASE_REF not available"
fi

echo "==> Search tables verified"
