#!/usr/bin/env bash
# Verifies the committed search artifacts still describe the locked SQLCipher pod, and that any
# token-affecting change carries a normalizer-version bump.
#
# The tokenizer tables, normalizer vectors and manifest are generated by probing the FTS5
# implementation inside Pods/SQLCipher. Nothing stops someone editing them by hand, and nothing
# stops a pod bump silently changing what the tokenizer does. Either way the on-device index would
# disagree with the code that queries it, and the failure is invisible until a user's search returns
# the wrong rows.
#
# **Fails closed.** An earlier version skipped the version-bump check when the base ref was
# unavailable, and CI checked out at depth 1 — so the check never ran and its absence looked like a
# pass. Missing ancestry is now an error, not a shrug.
#
#     scripts/verify-search-tables.sh <base-ref-or-sha>
#
# The base must be a real commit with a merge base against HEAD. CI passes the PR base SHA or, for
# pushes, the previous head.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

BASE_REF="${1:-}"
TABLES="Toj/Core/Search/SearchUnicodeTables.swift"
VECTORS="server/src/search-normalizer-vectors.json"
MANIFEST="Toj/Core/Search/search-tokenizer-manifest.json"

if [[ ! -f Pods/SQLCipher/sqlite3.c ]]; then
  echo "FAIL: Pods/SQLCipher/sqlite3.c missing — run 'pod install' first" >&2
  exit 2
fi

echo "==> Regenerating from Pods/SQLCipher ($(grep -m1 '#define SQLITE_VERSION ' Pods/SQLCipher/sqlite3.h | awk '{print $3}'))"

# Order matters: the manifest digests the other two, so they must be current first.
fail=0
for pair in "$TABLES:generate-search-unicode-tables.py" \
            "$VECTORS:generate-search-normalizer-vectors.py" \
            "$MANIFEST:generate-search-manifest.py"; do
  path="${pair%%:*}"
  script="${pair##*:}"
  tmp="$(mktemp)"
  python3 "scripts/$script" > "$tmp"
  if ! diff -q "$path" "$tmp" > /dev/null; then
    echo "FAIL: $path does not match a fresh probe of the locked pod." >&2
    echo "      Regenerate with: python3 scripts/$script > $path" >&2
    diff -u "$path" "$tmp" | head -40 >&2
    fail=1
  else
    echo "  ok  $path"
  fi
  rm -f "$tmp"
done
[[ $fail -eq 0 ]] || exit 1

# ---------------------------------------------------------------------------
# Version-bump enforcement
#
# A token-affecting change without a version bump leaves every existing install querying a new
# ruleset against an index built under the old one. The manifest makes this total: rather than
# grepping diff hunks for the token-affecting edits someone thought to enumerate, compare the
# digests, which cover classification, folding, the hand-written maps, and the token walker's
# actual output.
# ---------------------------------------------------------------------------

if [[ -z "$BASE_REF" ]]; then
  echo "FAIL: no base ref given. Pass the PR base SHA (or previous head for a push)." >&2
  echo "      Without it the version-bump check cannot run, and skipping it silently is how" >&2
  echo "      this check went unenforced before." >&2
  exit 1
fi

if ! base_sha="$(git rev-parse --verify --quiet "${BASE_REF}^{commit}")"; then
  echo "FAIL: base ref '$BASE_REF' is not a commit in this clone." >&2
  echo "      CI must check out with enough history (fetch-depth: 0) for the base to resolve." >&2
  exit 1
fi

if ! merge_base="$(git merge-base "$base_sha" HEAD 2>/dev/null)"; then
  echo "FAIL: no merge base between '$BASE_REF' and HEAD." >&2
  echo "      This is what a shallow (depth-1) checkout looks like: both commits exist but share" >&2
  echo "      no ancestry, so a diff against the base is meaningless." >&2
  exit 1
fi

digests_of() {  # $1 = git revision, or "" for the working tree
  if [[ -z "$1" ]]; then
    python3 -c 'import json,sys; print(json.dumps(json.load(open(sys.argv[1]))["digests"], sort_keys=True))' "$MANIFEST"
  else
    git show "$1:$MANIFEST" 2>/dev/null \
      | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin)["digests"], sort_keys=True))' 2>/dev/null \
      || echo "ABSENT"
  fi
}

version_of() {
  if [[ -z "$1" ]]; then
    python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["normalizerVersion"])' "$MANIFEST"
  else
    git show "$1:$MANIFEST" 2>/dev/null \
      | python3 -c 'import json,sys; print(json.load(sys.stdin)["normalizerVersion"])' 2>/dev/null \
      || echo "ABSENT"
  fi
}

base_digests="$(digests_of "$merge_base")"
head_digests="$(digests_of "")"
base_version="$(version_of "$merge_base")"
head_version="$(version_of "")"

report_digest_changes() {
  python3 - "$base_digests" "$head_digests" >&2 <<'PY'
import json, sys
base, head = json.loads(sys.argv[1]), json.loads(sys.argv[2])
for key in sorted(set(base) | set(head)):
    if base.get(key) != head.get(key):
        print(f"        {key}: {str(base.get(key))[:16]} -> {str(head.get(key))[:16]}", file=sys.stderr)
PY
}

if [[ "$base_digests" == "ABSENT" ]]; then
  echo "  --  manifest is new at this base; nothing to compare"
elif [[ "$base_digests" == "$head_digests" ]]; then
  echo "  ok  no token-affecting change since $(git rev-parse --short "$merge_base")"
else
  # Digests moved, so the version must move forward with them. Requiring a strict increase rather
  # than mere inequality closes two holes an equality check leaves open: a downgrade, and reusing a
  # version that already shipped. Either leaves installs holding an index built under different
  # rules while believing they are current — the exact failure this gate exists to prevent, and a
  # silent one, because the number looks deliberate.
  if [[ ! "$base_version" =~ ^[0-9]+$ ]] || [[ ! "$head_version" =~ ^[0-9]+$ ]]; then
    echo "FAIL: normalizerVersion must be an integer on both sides to be comparable." >&2
    echo "      base='$base_version' head='$head_version'" >&2
    report_digest_changes
    echo "      Set an integer normalizerVersion in $MANIFEST greater than the base, then" >&2
    echo "      regenerate with scripts/generate-search-manifest.py." >&2
    exit 1
  fi

  if (( head_version <= base_version )); then
    if (( head_version == base_version )); then
      echo "FAIL: token-affecting inputs changed but normalizerVersion is still $head_version." >&2
    else
      echo "FAIL: normalizerVersion went backwards, $base_version -> $head_version, while" >&2
      echo "      token-affecting inputs changed." >&2
    fi
    report_digest_changes
    echo "      Bump normalizerVersion in $MANIFEST above $base_version, keep" >&2
    echo "      SearchTextNormalizer.version in step, then regenerate with" >&2
    echo "      scripts/generate-search-manifest.py." >&2
    exit 1
  fi

  echo "  ok  token-affecting change with normalizerVersion $base_version -> $head_version"
fi

echo "==> Search artifacts verified"
